### ISSUE TITLE
Update an item

### ISSUE THREAD

**Issue by surya7765** [surya7765/recipeapp#1]
add placeholder to the update item page.

**Comment by Kinshu-Learner** [comment]
Could you describe the issue a bit better please?

**Comment by Bhavishya2912** [comment]
Pls assign this to me. I will work on this.

**Comment by surya7765** [comment]
> Could you describe the issue a bit better please?

the website is hosted and link is provided please see it once

**Comment by surya7765** [comment]
> Pls assign this to me. I will work on this.

Thanks for the update.

**Comment by Bhavishya2912** [comment]
Thanks
